title: Stack Problems
description: My Personal Stack Problems
author: Cassiano Campes
github: https://github.com/campescassiano
about: I'm a Ph.D. student working on Linux kernel. Here are the problems I had so far. Serve yourself!
disqus_shortname: phyloflash
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/campescassiano"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/cassianocampes"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/2031180/campescassiano"
    - icon: fa-github
      link: "https://github.com/campescassiano"
    - icon: fa-gitlab
      link: "https://gitlab.com/campescassiano"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://campescassiano.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
